import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useReactiveVar } from '@apollo/client';
import { isLoggedInVar } from '../lib/apolloClient';
import { graphql } from '../gql/gql';
const inter = Inter({ subsets: ['latin'] })

const IS_LOGGED_IN = graphql(/* GraphQL */ `
query isLoggedIn {
  isLoggedIn @client
}`);

export default function Home() {
  // const {
  //   data: {
  //     isLoggedIn,
  //   }
  // } = useQuery(IS_LOGGED_IN);
  const isLoggedIn = useReactiveVar(isLoggedInVar);
  const onClick = () => {
    isLoggedInVar(true);
  }
  console.log("isLoggedIn ", isLoggedIn);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {isLoggedIn ? '1' : '2'}
        <button onClick={onClick}>Click</button>
      </main>
    </>
  )
}
